services:
  db:
    image: postgres
    container_name: feedbackhub-db
    env_file:
        - .env
    ports:
      - "5432:5432"
    volumes:
      - feedbackhub_vol:/var/lib/postgresql
    restart: always
    networks:
      - feedbackhub_net

  backend:
    build: ./backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    networks:
      - feedbackhub_net
    env_file:
      - .env
    
  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - feedbackhub_net
    env_file:
      - .env


networks:
  feedbackhub_net:

volumes:
  feedbackhub_vol:      