services:
  db:
    image: postgres
    container_name: feedbackhub-db
    # env_file:
    #     - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - feedbackhub_vol:/var/lib/postgresql
    restart: always
    networks:
      - feedbackhub_net

  backend:
    image: backend
    container_name: feedbackhub-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: always
    networks:
      - feedbackhub_net
    # env_file:
    #   - .env
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@feedbackhub-db:5432/${POSTGRES_DB}

  frontend:
    image: frontend
    container_name: feedbackhub-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: always
    networks:
      - feedbackhub_net
    env_file:
      - .env


networks:
  feedbackhub_net:

volumes:
  feedbackhub_vol:      